### ISSUE TITLE
Can we add a network proxy option?

### ISSUE THREAD

**Issue by HuengchI** [merefield/discourse-chatbot#15]
I often encounter an issue while using the discourse-chatbot plugin, where the bot responds with the message `Sorry, I'm not well right now. Let's talk some other time. Meanwhile, please ask the admin to check the logs, thank you!` Upon checking the logs, I found several `ReadTimeout` errors, which may be due to network issues. Additionally, I noticed that the bot's response time varies; sometimes, it responds within seconds, while at other times, it takes several minutes, even though I've been using a ChatGPT premium account API key. Perhaps this issue is also related to the network.

Therefore, can we consider adding a proxy option to the plugin, similar to how we use `export http_proxy=http://server.com` in the terminal? I have already attempted to configure it in the `env` section of the discourse's `app.yml` file, but it appears that the plugin is not utilizing these environment variables. (I did not observe any records of the proxy client accessing the OpenAI Service in the logs).

**Comment by merefield** [comment]
I"m utilising this gem to abstract all of the API transactions:  https://github.com/alexrudall/ruby-openai

This means I'm not involved in dealing with this layer.  Perhaps your query is better handled on that repo?  I don't intend to change my allegiance to that gem for some time.

**Comment by merefield** [comment]
Closing due to lack of response

**Comment by merefield** [comment]
@HuengchI this is now implemented via #32

**Comment by HuengchI** [comment]
@merefield wow! so glad to hear it ^-^
