### ISSUE TITLE
Floating quick bot access button width doesn't adjust to text length

### ISSUE THREAD

**Issue by 37Rb** [merefield/discourse-chatbot#52]
If you customize js.chatbot.title_capitalized to text with a different length, the button size doesn't adjust to fit the text.

<img width="271" alt="Screenshot 2023-12-04 at 1 48 04 PM" src="https://github.com/merefield/discourse-chatbot/assets/82692355/6e7441ce-0b4c-454d-ba39-b401bd473125">

**Comment by merefield** [comment]
Addressed in #61 to your satisfaction, I hope?
